"""empty message

Revision ID: abc9005eb4b5
Revises: c7fa9ab644ff
Create Date: 2023-04-29 12:34:32.098156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc9005eb4b5'
down_revision = 'c7fa9ab644ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('identity', sa.String(length=250), nullable=True),
    sa.Column('main_text', sa.String(length=250), nullable=True),
    sa.Column('secondary_text', sa.String(length=250), nullable=True),
    sa.Column('price', sa.String(length=250), nullable=True),
    sa.Column('logo', sa.String(length=250), nullable=True),
    sa.Column('formality', sa.Integer(), nullable=True),
    sa.Column('main_color', sa.String(length=250), nullable=True),
    sa.Column('secondary_color', sa.String(length=250), nullable=True),
    sa.Column('aux_color', sa.String(length=250), nullable=True),
    sa.Column('ratio', sa.String(length=250), nullable=True),
    sa.Column('image_url', sa.String(length=250), nullable=True),
    sa.Column('contact_data', sa.String(length=250), nullable=True),
    sa.Column('cta', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('contact_data', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('facebook_profile', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('instagram_profile', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('tiktok_profile', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('identity', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('logo', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('main_color', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('secondary_color', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('aux_color', sa.String(length=250), nullable=True))
        batch_op.create_unique_constraint(None, ['contact_data'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('aux_color')
        batch_op.drop_column('secondary_color')
        batch_op.drop_column('main_color')
        batch_op.drop_column('logo')
        batch_op.drop_column('identity')
        batch_op.drop_column('tiktok_profile')
        batch_op.drop_column('instagram_profile')
        batch_op.drop_column('facebook_profile')
        batch_op.drop_column('contact_data')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.drop_table('post')
    # ### end Alembic commands ###
